#  ___        _  ___           __ _
# | _ \___ __| |/ __|_ _ __ _ / _| |_   ___ _ _ __ _
# |   / -_) _` | (__| '_/ _` |  _|  _|_/ _ \ '_/ _` |
# |_|_\___\__,_|\___|_| \__,_|_|  \__(_)___/_| \__, |
#                                              |___/
#
# RedCraftMongoStats config
sync-ticks-interval: 600 # Default sync every 30 secs
debug-sync: false # Prints debug to console (verbose), not recommended on production

# Database related settings
mongo-uri: "mongodb://username:password@localhost:27017/?retryWrites=true"
mongo-database: "redcraft_stats"
mongo-collection: "test"
