name: RedCraftMongoStats
main: org.redcraft.redcraftmongostats.RedCraftMongoStats
version: 0.0.1-SNAPSHOT
api-version: 1.17
author: RedCraft
authors: [lululombard]
website: redcraft.org
commands:
  syncstats:
    description: Sync stats to MongoDB
    usage: /syncstats
    permission: redcraftmongostats.syncstats
