name: Test project

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.16
        uses: actions/setup-java@v1
        with:
          java-version: 1.16

      - name: Test with Maven
        run: mvn test
